substitutions:
  # Region where Cloud Run, Scheduler, and Artifact Registry operate.
  _REGION: australia-southeast1
  # Cloud Run service hosting the ingestion pipeline.
  _SERVICE: all_brands_nzta_deregistered_vins_sync
  # Artifact Registry repository used for versioned images.
  _REPO: all_brands_nzta_deregistered_vins

options:
  logging: NONE

steps:
  # 1) Guarantee the GCS landing bucket exists (no delete to retain audit files).
  - name: gcr.io.google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        BUCKET="${_GCS_BUCKET:-all-brands-nzta-deregistered-vins-temp-do-not-delete}"
        if ! gsutil ls -b "gs://${BUCKET}" >/dev/null 2>&1; then
          gsutil mb -l $_REGION "gs://${BUCKET}"
        fi

  # 1) Guarantee the Pub/Sub topic exists so later steps can bind to it.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gcloud pubsub topics describe all_brands_nzta_deregistered_vins_sync_trigger >/dev/null 2>&1 || \
        gcloud pubsub topics create all_brands_nzta_deregistered_vins_sync_trigger

  # 2) Build the Cloud Run container image from the current workspace.
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/adh-data-utopia/$_REPO/$_SERVICE:$SHORT_SHA",
        ".",
      ]

  # 3) Push the image to Artifact Registry so Cloud Run can pull it.
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/adh-data-utopia/$_REPO/$_SERVICE:$SHORT_SHA",
      ]

  # 4) Deploy (or update) the Cloud Run service with secret-driven env vars.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","$_SERVICE",
        "--image","$_REGION-docker.pkg.dev/adh-data-utopia/$_REPO/$_SERVICE:$SHORT_SHA",
        "--region","$_REGION",
        "--platform","managed",
        "--allow-unauthenticated",
        "--timeout","900",
        "--max-instances","1",
        "--set-env-vars",
        "FTP_CONFIG_SECRET=${_FTP_CONFIG_SECRET},SUGAR_CONFIG_SECRET=${_SUGAR_CONFIG_SECRET},FTP_REMOTE_PATH=${_FTP_REMOTE_PATH},FTP_FILE_PATTERN=${_FTP_FILE_PATTERN},GCS_BUCKET=${_GCS_BUCKET},GCS_RAW_PREFIX=${_GCS_RAW_PREFIX},GCS_PROCESSED_PREFIX=${_GCS_PROCESSED_PREFIX},GCS_ERROR_PREFIX=${_GCS_ERROR_PREFIX},ALLOWED_MAKES=${_ALLOWED_MAKES},BQ_STAGE_DATASET=${_BQ_STAGE_DATASET},BQ_STAGE_TABLE=${_BQ_STAGE_TABLE},BQ_STAGE_LOCATION=${_BQ_STAGE_LOCATION},EMAIL_SENDER=${_EMAIL_SENDER},EMAIL_RECIPIENTS=${_EMAIL_RECIPIENTS},SMTP_HOST=${_SMTP_HOST},SMTP_PORT=${_SMTP_PORT},SMTP_USERNAME=${_SMTP_USERNAME},SMTP_PASSWORD=${_SMTP_PASSWORD},SMTP_USE_TLS=${_SMTP_USE_TLS},SMTP_TIMEOUT=${_SMTP_TIMEOUT}"
      ]

  # 5) Let the Pub/Sub push identity invoke the Cloud Run endpoint.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","services","add-iam-policy-binding","$_SERVICE",
        "--region","$_REGION",
        "--member","serviceAccount:ib4t-integration@adh-data-utopia.iam.gserviceaccount.com",
        "--role","roles/run.invoker"
      ]

  # 6) Recreate the push subscription pointing to the fresh service URL.
  - name: gcr.io.google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        SERVICE_URL="$(gcloud run services describe $_SERVICE --region $_REGION --format='value(status.url)')"
        if gcloud pubsub subscriptions describe all_brands_nzta_deregistered_vins_runner >/dev/null 2>&1; then
          gcloud pubsub subscriptions delete all_brands_nzta_deregistered_vins_runner --quiet
        fi
        gcloud pubsub subscriptions create all_brands_nzta_deregistered_vins_runner \
          --topic=all_brands_nzta_deregistered_vins_sync_trigger \
          --push-endpoint="${SERVICE_URL}/" \
          --push-auth-service-account="ib4t-integration@adh-data-utopia.iam.gserviceaccount.com"

  # 7) Create or update the Scheduler job that publishes weekly triggers.
  - name: gcr.io.google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        JOB_NAME="all_brands_nzta_deregistered_vins_weekly"
        SCHEDULE="0 3 * * 2"  # Tuesdays at 03:00 NZT.
        TZ="Pacific/Auckland"
        if gcloud scheduler jobs describe ${JOB_NAME} >/dev/null 2>&1; then
          gcloud scheduler jobs update pubsub ${JOB_NAME} \
            --schedule="${SCHEDULE}" \
            --time-zone="${TZ}" \
            --topic=all_brands_nzta_deregistered_vins_sync_trigger \
            --message-body="{}"
        else
          gcloud scheduler jobs create pubsub ${JOB_NAME} \
            --schedule="${SCHEDULE}" \
            --time-zone="${TZ}" \
            --topic=all_brands_nzta_deregistered_vins_sync_trigger \
            --message-body="{}"
        fi

images:
  # Artifact reference recorded for reproducibility/auditing.
  - "$_REGION-docker.pkg.dev/adh-data-utopia/$_REPO/$_SERVICE:$SHORT_SHA"
